# To change this template, choose Tools | Templates
# and open the template in the editor.
usuario=sm_t0ry_user
contrasena=nSESeYtHWZi4GvnFNjQfV8fsXzVZ3Qdp
iphost=dpg-d8frv6d8nd3s738v7s6g-a
puerto=5432
namedb=sm_t0ry
gestor=POSTGRES
